language: python
python:
  - "3.6"
cache: pip
git:
  depth: false

install:
  #- pip install -r requirements.txt
  - ./rebuild.sh   
script:
  #- gunicorn --bind 0.0.0.0:9891 --daemon --workers 1 wsgi:app
  - pip install -r requirements.txt
  - python3 testsendreq.py
